pipeline {
    agent any
    environment {
        WORKSPACE="/var/lib/jenkins/workspace/docker-framework/docker-framework"
    }
    stages {
        stage('Git Clone') {
           steps {
               echo "Check out Git Repo using Master Branch"
               git branch: "master",
               credentialsId: 'nabarunsen',
               url: 'https://github.com/nabarunsen/kubernetes_example.git'
               echo "WORKSPACE is ${WORKSPACE}"           
	   }
        }
        stage('Build') {
	   steps {
	       sh "cd ${WORKSPACE}"
               echo "Building application and Docker image"
               sh "${WORKSPACE}/build.sh"
       	    }

         }
     }
}
