pipeline {
 
    options {
        // Build auto timeout
        timeout(time: 60, unit: 'MINUTES')
    }

    environment {
        WORKSPACE="/var/lib/jenkins/gradle-framework"
    }
   stages {
            stage('Git clone and setup') {

             steps {
                        echo "Check out Git Repo using Master Branch"
                        git branch: "master",
                        credentialsId: 'nabarunsen',
                        url: 'https://github.com/nabarunsen/kubernetes_example.git'
                        echo "WORKSPACE is ${WORKSPACE}"
                }

                steps('Build the Docker Images') {
                        cd ${WORKSPACE}
                        echo "Building application and Docker image"
                        sh "${WORKSPACE}/build.sh"
                }
             }
   }
}
